package com.example.sleepshakker

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.TypeConverters
import kotlinx.parcelize.Parcelize
import java.util.Calendar // Keep for understanding repeatDays, though Calendar itself isn't stored

@Parcelize
@Entity(tableName = "alarms")
@TypeConverters(DaysSetConverter::class)
data class AlarmItem(
    @PrimaryKey(autoGenerate = true)
    var id: Long = 0L, // Primary key, auto-generated by Room if 0
    var timeInMillis: Long,
    var message: String = "Alarm",
    var isEnabled: Boolean = true,
    var repeatDays: Set<Int>? = null, // Set of Calendar.DAY_OF_WEEK
    var dismissOption: String? = null
) : Parcelable
// Note: equals() and hashCode() are often omitted for Room entities
// unless specific comparison logic beyond the ID is frequently needed.
// Room uses the primary key for its own comparisons and change tracking.
